/** Shared project peeks — keep in sync with homepage tiles. */
export const PROJECTS = [
  {
    src: "./archive/previews/1.jpeg",
    alt: "Cartographic (Spatial) Struggle of Performing Corporeality",
    href: "./project.html",
    w: 750,
    h: 422,
    oy: -1.15,
    rot: -3.2,
  },
  {
    src: "./archive/previews/2.jpg",
    alt: "Reals",
    w: 750,
    h: 422,
    oy: -1.85,
    rot: 2.4,
  },
  {
    src: "./archive/previews/3.jpg",
    alt: "The Hours That Hold the Figure and the Form",
    w: 750,
    h: 500,
    oy: 0.45,
    rot: 1.8,
  },
  {
    src: "./archive/previews/4.jpg",
    alt: "Dispersed Agency",
    w: 750,
    h: 427,
    oy: 0.35,
    rot: -2.1,
  },
  {
    src: "./archive/previews/5.jpg",
    alt: "Pale Light",
    w: 750,
    h: 488,
    oy: 2.2,
    rot: 3.6,
  },
  {
    src: "./archive/previews/6.jpg",
    alt: "The Common Box",
    w: 750,
    h: 423,
    oy: 2.35,
    rot: -1.4,
  },
  {
    src: "./archive/previews/7.JPG",
    alt: "Human Experience",
    w: 750,
    h: 563,
    oy: -0.95,
    rot: -4.1,
  },
  {
    src: "./archive/previews/8.jpg",
    alt: "I Talk 4Real",
    w: 750,
    h: 500,
    oy: -0.7,
    rot: 2.8,
  },
  {
    src: "./archive/previews/9.jpg",
    alt: "Chains",
    w: 750,
    h: 532,
    oy: -1.2,
    rot: 1.2,
  },
  {
    src: "./archive/previews/10.jpg",
    alt: "Dark Nature",
    w: 750,
    h: 478,
    oy: 2.7,
    rot: -2.7,
  },
  {
    src: "./archive/previews/11.jpg",
    alt: "Maps",
    w: 750,
    h: 421,
    oy: 1.45,
    rot: 4.0,
  },
];
